language: generic
services:
  - docker

before_install:
  - docker build -t tbheng/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true tbheng/react-test npm test

after_success:
  - docker build -t tbheng/multi-client ./client
  - docker build -t tbheng/multi-nginx ./nginx
  - docker build -t tbheng/multi-server ./server
  - docker build -t tbheng/multi-worker ./worker

  # Login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Push images to Docker Hub
  - docker push tbheng/multi-client
  - docker push tbheng/multi-nginx
  - docker push tbheng/multi-server
  - docker push tbheng/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-028920554699"
  bucket_path: "docker-multi"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
